# Generated by Django 5.1.1 on 2024-12-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_paciente', '0001_initial'),
    ]

    operations = [
    ]
